management:
  otlp:
    metrics:
      export:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
        step: 2s
        connect-timeout: 1s
        read-timeout: 2s
  tracing:
    export:
      enabled: true
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
          connect-timeout: 1s
          timeout: 2s
  observations:
    key-values:
      service: flash-booking
